# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jllodra/workspace/ncdump-json/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jllodra/workspace/ncdump-json

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jllodra/workspace/ncdump-json/CMakeFiles /home/jllodra/workspace/ncdump-json/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jllodra/workspace/ncdump-json/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncdump-json

# Build rule for target.
ncdump-json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ncdump-json
.PHONY : ncdump-json

# fast build rule for target.
ncdump-json/fast:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/build
.PHONY : ncdump-json/fast

dumplib.o: dumplib.c.o
.PHONY : dumplib.o

# target to build an object file
dumplib.c.o:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/dumplib.c.o
.PHONY : dumplib.c.o

dumplib.i: dumplib.c.i
.PHONY : dumplib.i

# target to preprocess a source file
dumplib.c.i:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/dumplib.c.i
.PHONY : dumplib.c.i

dumplib.s: dumplib.c.s
.PHONY : dumplib.s

# target to generate assembly for a file
dumplib.c.s:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/dumplib.c.s
.PHONY : dumplib.c.s

indent.o: indent.c.o
.PHONY : indent.o

# target to build an object file
indent.c.o:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/indent.c.o
.PHONY : indent.c.o

indent.i: indent.c.i
.PHONY : indent.i

# target to preprocess a source file
indent.c.i:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/indent.c.i
.PHONY : indent.c.i

indent.s: indent.c.s
.PHONY : indent.s

# target to generate assembly for a file
indent.c.s:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/indent.c.s
.PHONY : indent.c.s

ncdump.o: ncdump.c.o
.PHONY : ncdump.o

# target to build an object file
ncdump.c.o:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/ncdump.c.o
.PHONY : ncdump.c.o

ncdump.i: ncdump.c.i
.PHONY : ncdump.i

# target to preprocess a source file
ncdump.c.i:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/ncdump.c.i
.PHONY : ncdump.c.i

ncdump.s: ncdump.c.s
.PHONY : ncdump.s

# target to generate assembly for a file
ncdump.c.s:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/ncdump.c.s
.PHONY : ncdump.c.s

nctime.o: nctime.c.o
.PHONY : nctime.o

# target to build an object file
nctime.c.o:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/nctime.c.o
.PHONY : nctime.c.o

nctime.i: nctime.c.i
.PHONY : nctime.i

# target to preprocess a source file
nctime.c.i:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/nctime.c.i
.PHONY : nctime.c.i

nctime.s: nctime.c.s
.PHONY : nctime.s

# target to generate assembly for a file
nctime.c.s:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/nctime.c.s
.PHONY : nctime.c.s

vardata.o: vardata.c.o
.PHONY : vardata.o

# target to build an object file
vardata.c.o:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/vardata.c.o
.PHONY : vardata.c.o

vardata.i: vardata.c.i
.PHONY : vardata.i

# target to preprocess a source file
vardata.c.i:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/vardata.c.i
.PHONY : vardata.c.i

vardata.s: vardata.c.s
.PHONY : vardata.s

# target to generate assembly for a file
vardata.c.s:
	$(MAKE) -f CMakeFiles/ncdump-json.dir/build.make CMakeFiles/ncdump-json.dir/vardata.c.s
.PHONY : vardata.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... ncdump-json"
	@echo "... rebuild_cache"
	@echo "... dumplib.o"
	@echo "... dumplib.i"
	@echo "... dumplib.s"
	@echo "... indent.o"
	@echo "... indent.i"
	@echo "... indent.s"
	@echo "... ncdump.o"
	@echo "... ncdump.i"
	@echo "... ncdump.s"
	@echo "... nctime.o"
	@echo "... nctime.i"
	@echo "... nctime.s"
	@echo "... vardata.o"
	@echo "... vardata.i"
	@echo "... vardata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

